### ISSUE TITLE
Rating

### ISSUE THREAD

**Issue by vasilisvg** [larsdouweschuitema/minor-css-to-the-rescue#10]
Dit ziet er nog niet zo goed uit. En kijk ook eens of je dit in context kunt plaatsen. Hoe ziet het er uit in een media-item?

**Comment by larsdouweschuitema** [comment]
Updated rating to hide labels for users that do not require screen readers because the emoji explain themselves. Radio button on top of the emoji but visibly hidden so that the user can select the rating using the emoji's. Also added a :hover and :focus state because the user needs to know he can select the emoji.
