### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by vasilisvg** [larsdouweschuitema/minor-css-to-the-rescue#12]
[Dit is misschien niet zo'n slimme CSS regel](https://github.com/larsdouweschuitema/minor-css-to-the-rescue/blob/master/week-2/assets/css/base/reset.css#L26). Hierdoor wordt focus onzichtbaar als je het later vergeet te stylen (zoals je hier en daar hebt gedaan)
Op zich ziet je code er aardig uit. Ik vraag me soms af of de code die je in een mediaquery stopt wel echt in een mediaquery moet staan. 
Ik vind het nog wel wat weinig allemaal. Je zal aan de bak moeten.

**Comment by larsdouweschuitema** [comment]
Removed the reset of the :focus. Like you said: it is better to keep a default :focus style so that a developer does not forget to style it and can remove it when needed for a specific element. It turned out that using a clear default :focus style improves the usability of the user, even though some would say it looks less appealing. "Usability over aesthetics".
